
[remappings]
enabled = true

[dependencies]
"@openzeppelin-contracts" = "5.0.2"
forge-std = { version = "1.9.4", url = "https://soldeer-revisions.s3.amazonaws.com/forge-std/1_9_4_25-10-2024_14:36:59_forge-std-1.9.zip" }
